# Generated by Django 4.1.6 on 2023-02-19 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletinboard', '0002_alter_bulletin_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='bulletin',
        ),
    ]
