# Generated by Django 4.1.6 on 2023-03-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletinboard', '0006_bulletin_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='slug',
            field=models.SlugField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='title',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
