# Generated by Django 4.1.6 on 2023-03-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletinboard', '0007_alter_bulletin_slug_alter_bulletin_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='slug',
            field=models.SlugField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
